UniveristyWevApp/UniveristyWevApp/Models/ClassRoom.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniveristyWevApp.Models
{
    public class ClassRoom
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
         [Required]
        [DisplayName("Course")]
        public int CourseId { get; set; }
         [Required]
        [DisplayName("Room")]
        public int RoomId { get; set; }
         [Required]
        [DisplayName("Day")]

        public int  DayId { get; set; }
         [Required]
        [DisplayName("From")]
        public DateTime StartTime { get; set; }
         [Required]
        [DisplayName("To")]
        public DateTime Endtime { get; set; }
         public bool AlloctionStaus { get; set; }
    }
}

UniveristyWevApp/UniveristyWevApp/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniveristyWevApp.BLL;
using UniveristyWevApp.Manager;
using UniveristyWevApp.Models;

namespace UniveristyWevApp.Controllers
{
    public class ClassRoomController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        CourseManager courseManager = new CourseManager();
        RoomManager roomManager = new RoomManager();
        DayManager dayManager = new DayManager();
        ClassRoomManager classRoomManager = new ClassRoomManager();

        private List<TempClassSchedule> classRooms;
        //
        // GET: /ClassRoom/
        public ActionResult Index()
        {
            ViewBag.Departments = departmentManager.GetAll();
            classRooms = classRoomManager.GetAllClassSchedules;
            ViewBag.ClassSchedule = classRooms;
            return View();
        }


        // GET: /ClassRoom/Create
        public ActionResult Save()
        {
            List<Day> days = dayManager.GetAllDays.ToList();
            ViewBag.Days = days;
            List<Room> rooms = roomManager.GetAllRooms.ToList();
            ViewBag.Rooms = rooms;
            ViewBag.Departments = departmentManager.GetAll();
            ViewBag.Courses = courseManager.GetAll;
            return View();
        }

        //
        // POST: /ClassRoom/Create
        [HttpPost]
        public ActionResult Save(ClassRoom classRoom)
        {
            try
            {

                ViewBag.alart = classRoomManager.Save(classRoom);

                List<Day> days = dayManager.GetAllDays.ToList();
                ViewBag.Days = days;
                List<Room> rooms = roomManager.GetAllRooms.ToList();
                ViewBag.Rooms = rooms;
                var rr = departmentManager.GetAll();
                ViewBag.Departments = rr;
                ViewBag.Courses = courseManager.GetAll;
                return View();
            }
            catch
            {
                return View();
            }
        }
        public JsonResult GetClassScheduleByDepartment(int departmentId)
        {
            var courses = courseManager.GetCourseByDepartmentId(departmentId);

            List<object> clsSches = new List<object>();

            foreach (var course in courses)
            {
                var scheduleInfo = classRoomManager.GetAllClassSchedulesByDeparmentId(departmentId, course.Id);
                if (scheduleInfo == "")
                {
                    scheduleInfo = "Not sheduled yet";
                }


                var clsSch = new
                {
                    CourseCode = course.Code,
                    CourseName = course.Name,
                    ScheduleInfo = scheduleInfo
                };
                clsSches.Add(clsSch);
            }
            return Json(clsSches, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            IEnumerable<Course> courses = courseManager.GetAll;
            var courseList = courses.ToList().FindAll(c => c.DepartmentId == departmentId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult UnAllocateClassRoom()
        {
            ViewBag.alart = new AlartType("Unassign all the class rooms.", "danger");
            return View();
        }
        [HttpPost]
        public ActionResult UnAllocateClassRoom(int? id)
        {
            ViewBag.alart = classRoomManager.UnAllocateClassRoom();
            return View();
        }
	}
}

UniveristyWevApp/UniveristyWevApp/Views/ClassRoom/Index.cshtml
@model UniveristyWevApp.Models.TempClassSchedule
@{
    ViewBag.Title = "View Class Schedule";
}

<div class="col-sm-12" style="padding-top: 30px">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center; height: 40px; padding-top: 10px;">
            <p><strong>Class Schedule and Room Allocation Information</strong></p>
        </div>
        <div class="panel-body">
            <table class="table" >
                <tr>
                    <td>@Html.LabelFor(x => x.DepartmentId)</td>
                    <td>
                        <select id="DepartmentId" class="form-control">
                            <option value="">Select department</option>
                            @foreach (var dept in ViewBag.Departments)
                            {
                                <option value="@dept.Id">@dept.Name</option>
                            }
                        </select>
                    </td>
                    <td>@Html.ValidationMessageFor(m => m.DepartmentId)</td>
                </tr>
            </table>
            <table id="SchduleTable" class=" table table-hover table-bordered">
                <thead class="table table-striped">
                    <tr>
                        <th  style="width: 150px;">Course Code</th>
                        <th  style="width: 220px;">Course Name</th>
                        <th style="width: 350px;">Schedule Info</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {
                $('#SchduleTable tbody').empty();
                var deptId = $("#DepartmentId").val();
                var json = { departmentId: deptId, };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetClassScheduleByDepartment", "ClassRoom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#SchduleTable tbody").append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.ScheduleInfo + '</td></tr>');
                        });
                    }
                });
            });
        });
    </script>
}

UniveristyWevApp/UniveristyWevApp/Views/ClassRoom/Save.cshtml
@using UniveristyWevApp.Models
@model UniveristyWevApp.Models.ClassRoom
@{
    ViewBag.Title = "Add Class Schedule";
    AlartType alartType = ViewBag.alart;

}

@section Style
{
<link href="~/Content/mobiscroll-2.9.5.full.min.css" rel="stylesheet" />
    <style>
        .field-validation-error {
            color: red;
            font-style: italic;
        }
    </style>
}
<div class="col-sm-12" style="padding-top: 30px">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center; height: 40px; padding-top: 10px;"><p><strong>Allocate Classrooms</strong></h4></div>
        <div class="panel-body">
            @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "saveClassScedule" }))
            {

                if (ViewBag.alart != null)
                {
                    <div class="alert alert-@alartType.Type">@alartType.Message</div>

                }


                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.LabelFor(model => model.DepartmentId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="DepartmentId" name="DepartmentId" class="form-control">
                                <option value="">Select.....</option>
                                @foreach (var dept in ViewBag.Departments)
                                {
                                    <option value="@dept.Id">@dept.Name</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(model => model.DepartmentId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CourseId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="CourseId" name="CourseId" class="form-control">
                                <option value="">..Select..</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.CourseId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.RoomId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="RoomId" name="RoomId" class="form-control">
                                <option value="">..Select..</option>
                                @foreach (var room in ViewBag.Rooms)
                                {
                                    <option value="@room.Id">@room.Name</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(model => model.RoomId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DayId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="DayId" name="DayId" class="form-control">
                                <option value="">Select.....</option>
                                @foreach (var day in ViewBag.Days)
                                {
                                    <option value="@day.Id">@day.Name</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(model => model.DayId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.StartTime, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.StartTime)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Endtime, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Endtime, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Endtime)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


@section scripts{
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/mobiscroll-2.9.5.full.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#StartTime").mobiscroll({ preset: 'time', 'theme': 'material' });
            $("#Endtime").mobiscroll({ preset: 'time', 'theme': 'material' });

            $("#saveClassScedule").validate({
                rules: {
                    CourseId: "required",
                    RoomId: "required",
                    DayId: "required",
                    StartTime: "required",
                    DepartmentId: "required",
                    Endtime: "required"

                },
                messages: {
                    CourseId: "Please Select  Course!",

                    RoomId: "Please Select room!",
                    DayId: "Please Select day!",
                    StartTime: "Select Start time!",
                    DepartmentId: "Please select department!",
                    Endtime: "Please select End time!"
                }
            });

            $("#DepartmentId").change(function () {
                var deptId = $("#DepartmentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="">Select Course</option>');

                var json = { departmentId: deptId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByDepartmentId", "ClassRoom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {
                            //alert(key);
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');

                        });
                    }
                });


            });



        });
    </script>
}

UniveristyWevApp/UniveristyWevApp/Views/ClassRoom/UnAllocateClassRoom.cshtml
@using UniveristyWevApp.Models
@{
    ViewBag.Title = "UnAllocateClassRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
    AlartType alartType = ViewBag.alart;
}

<div class="col-sm-12" style="padding-top: 30px">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center; height: 40px; padding-top: 10px;"><p><strong>Unallocate All Classrooms</strong></h4></div>
        <div class="panel-body">
            <form method="POST">
                @if (ViewBag.alart != null)
                {
                    <div class="alert alert-@alartType.Type">@alartType.Message</div>

                }
                <input type="submit" class="btn btn-danger btn-lg" value="Unallocate Class Rooms" data-confirm="Are you sure to UnAssign All Class Room?" />
            </form>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            jQuery('[data-confirm]').click(function (e) {
                if (!confirm(jQuery(this).attr("data-confirm"))) {
                    e.preventDefault();
                }
            });
        });
    </script>
}